Running ./main gives the following output. Note that destruction of elements
in partially allocated array are automatically handled by new[] by calling
the destructors of already allocated elements. Hence, there is nothing to
delete if new fails :)

Trying outer!
	Tring constructor!
	Creating object 1
	Tring constructor!
	Creating object 2
	Tring constructor!
	Creating object 3
	Tring constructor!
	Creating object 4
	Tring constructor!
	THROWN: Catching constructor!
	max number of objects reached
	Destroying object 4
	Destroying object 3
	Destroying object 2
	Destroying object 1
Catching outer!
